// Centralized mock data for the application
// This allows all pages to share the same data source

export const mockCustomers = [
  {
    id: 1,
    name: "Carlos García López",
    email: "carlos.garcia@email.com",
    phone: "+34 612 345 678",
    address: "Calle Principal 123",
    city: "Madrid",
    postal_code: "28001",
    notes: "Cliente frecuente, paga a tiempo",
    created_at: "2025-01-15",
    appointments_count: 8,
    total_spent: 1250.5,
  },
  {
    id: 2,
    name: "María López Rodríguez",
    email: "maria.lopez@email.com",
    phone: "+34 623 456 789",
    address: "Avenida Central 456",
    city: "Barcelona",
    postal_code: "08002",
    notes: "Nuevo cliente",
    created_at: "2025-09-20",
    appointments_count: 2,
    total_spent: 350.0,
  },
  {
    id: 3,
    name: "Juan Martínez Pérez",
    email: "juan.martinez@email.com",
    phone: "+34 634 567 890",
    address: "Plaza Mayor 789",
    city: "Valencia",
    postal_code: "46001",
    notes: "Requiere seguimiento",
    created_at: "2025-06-10",
    appointments_count: 5,
    total_spent: 890.75,
  },
  {
    id: 4,
    name: "Ana Fernández García",
    email: "ana.fernandez@email.com",
    phone: "+34 645 678 901",
    address: "Calle Secundaria 321",
    city: "Sevilla",
    postal_code: "41001",
    notes: "VIP - Descuento especial",
    created_at: "2025-03-05",
    appointments_count: 12,
    total_spent: 2150.25,
  },
]

export const mockInvoices = [
  {
    id: 1,
    invoice_number: "INV-2025-001",
    customer_name: "Carlos García López",
    customer_email: "carlos.garcia@email.com",
    issue_date: "2025-10-20",
    due_date: "2025-11-20",
    subtotal: 450.0,
    tax: 94.5,
    total: 544.5,
    status: "paid" as const,
    notes: "Pago recibido el 2025-10-25",
    items: [
      { id: 1, description: "Cambio de aceite", quantity: 1, unit_price: 50.0 },
      { id: 2, description: "Filtro de aire", quantity: 1, unit_price: 25.0 },
      { id: 3, description: "Revisión general", quantity: 1, unit_price: 375.0 },
    ],
  },
  {
    id: 2,
    invoice_number: "INV-2025-002",
    customer_name: "María López Rodríguez",
    customer_email: "maria.lopez@email.com",
    issue_date: "2025-10-15",
    due_date: "2025-11-15",
    subtotal: 350.0,
    tax: 73.5,
    total: 423.5,
    status: "pending" as const,
    notes: "Pendiente de pago",
    items: [
      { id: 1, description: "Pastillas de freno", quantity: 1, unit_price: 120.0 },
      { id: 2, description: "Discos de freno", quantity: 2, unit_price: 80.0 },
      { id: 3, description: "Mano de obra", quantity: 1, unit_price: 70.0 },
    ],
  },
  {
    id: 3,
    invoice_number: "INV-2025-003",
    customer_name: "Juan Martínez Pérez",
    customer_email: "juan.martinez@email.com",
    issue_date: "2025-09-15",
    due_date: "2025-10-15",
    subtotal: 200.0,
    tax: 42.0,
    total: 242.0,
    status: "overdue" as const,
    notes: "Vencida desde hace 13 días",
    items: [
      { id: 1, description: "Neumáticos (4 unidades)", quantity: 4, unit_price: 45.0 },
      { id: 2, description: "Balanceo y alineación", quantity: 1, unit_price: 20.0 },
    ],
  },
  {
    id: 4,
    invoice_number: "INV-2025-004",
    customer_name: "Ana Fernández García",
    customer_email: "ana.fernandez@email.com",
    issue_date: "2025-10-25",
    due_date: "2025-11-25",
    subtotal: 500.0,
    tax: 105.0,
    total: 605.0,
    status: "pending" as const,
    notes: "Factura reciente",
    items: [
      { id: 1, description: "Reparación de motor", quantity: 1, unit_price: 400.0 },
      { id: 2, description: "Piezas de repuesto", quantity: 1, unit_price: 100.0 },
    ],
  },
]

export const mockRepairOrders = [
  {
    id: 1,
    order_number: "RO-2025-001",
    customer_name: "Carlos García López",
    vehicle_info: "Toyota Corolla 2020 - Matrícula 1234 ABC",
    description: "Revisión general y cambio de aceite",
    status: "in_progress" as const,
    estimated_cost: 150.0,
    actual_cost: null,
    start_date: "2025-10-28",
    completion_date: null,
    notes: "Cliente requiere trabajo urgente",
    items: [
      { id: 1, description: "Cambio de aceite", quantity: 1, unit_price: 50.0 },
      { id: 2, description: "Filtro de aire", quantity: 1, unit_price: 25.0 },
      { id: 3, description: "Revisión general", quantity: 1, unit_price: 75.0 },
    ],
  },
  {
    id: 2,
    order_number: "RO-2025-002",
    customer_name: "María López Rodríguez",
    vehicle_info: "Ford Focus 2018 - Matrícula 5678 XYZ",
    description: "Reparación de frenos",
    status: "pending" as const,
    estimated_cost: 350.0,
    actual_cost: null,
    start_date: null,
    completion_date: null,
    notes: "Espera aprobación del cliente",
    items: [
      { id: 1, description: "Pastillas de freno", quantity: 1, unit_price: 120.0 },
      { id: 2, description: "Discos de freno", quantity: 2, unit_price: 80.0 },
      { id: 3, description: "Mano de obra", quantity: 1, unit_price: 150.0 },
    ],
  },
  {
    id: 3,
    order_number: "RO-2025-003",
    customer_name: "Juan Martínez Pérez",
    vehicle_info: "Volkswagen Golf 2019 - Matrícula 9012 DEF",
    description: "Cambio de neumáticos",
    status: "completed" as const,
    estimated_cost: 200.0,
    actual_cost: 210.0,
    start_date: "2025-10-20",
    completion_date: "2025-10-22",
    notes: "Trabajo completado satisfactoriamente",
    items: [
      { id: 1, description: "Neumáticos (4 unidades)", quantity: 4, unit_price: 45.0 },
      { id: 2, description: "Balanceo y alineación", quantity: 1, unit_price: 30.0 },
    ],
  },
]

export const mockInventory = [
  {
    id: 1,
    name: "Aceite de Motor 5W-30",
    sku: "OIL-5W30-5L",
    category: "Fluidos",
    quantity: 12,
    min_quantity: 10,
    unit_price: 25.5,
    supplier: "Castrol",
    last_restocked: "2025-10-15",
    description: "Aceite sintético de motor 5W-30, 5 litros",
  },
  {
    id: 2,
    name: "Filtro de Aire",
    sku: "FILTER-AIR-001",
    category: "Filtros",
    quantity: 3,
    min_quantity: 8,
    unit_price: 12.0,
    supplier: "Bosch",
    last_restocked: "2025-09-20",
    description: "Filtro de aire estándar para motores gasolina",
  },
  {
    id: 3,
    name: "Pastillas de Freno",
    sku: "BRAKE-PAD-FRONT",
    category: "Frenos",
    quantity: 8,
    min_quantity: 6,
    unit_price: 45.0,
    supplier: "ATE",
    last_restocked: "2025-10-10",
    description: "Pastillas de freno delanteras, juego completo",
  },
  {
    id: 4,
    name: "Batería 12V 60Ah",
    sku: "BATT-12V-60AH",
    category: "Eléctrico",
    quantity: 2,
    min_quantity: 3,
    unit_price: 85.0,
    supplier: "Varta",
    last_restocked: "2025-08-30",
    description: "Batería de coche 12V 60Ah",
  },
  {
    id: 5,
    name: "Correa de Distribución",
    sku: "BELT-DIST-001",
    category: "Correas",
    quantity: 5,
    min_quantity: 4,
    unit_price: 35.0,
    supplier: "Gates",
    last_restocked: "2025-10-05",
    description: "Correa de distribución universal",
  },
  {
    id: 6,
    name: "Bujías NGK",
    sku: "SPARK-NGK-001",
    category: "Encendido",
    quantity: 20,
    min_quantity: 10,
    unit_price: 8.5,
    supplier: "NGK",
    last_restocked: "2025-10-20",
    description: "Bujías de encendido NGK estándar",
  },
]

export const mockAppointments = [
  {
    id: 1,
    customer_name: "Carlos García",
    customer_phone: "+34 612 345 678",
    appointment_date: "2025-10-28T10:00:00",
    status: "confirmed" as const,
    description: "Revisión general y cambio de aceite",
    estimated_duration: 60,
  },
  {
    id: 2,
    customer_name: "María López",
    customer_phone: "+34 623 456 789",
    appointment_date: "2025-10-28T14:30:00",
    status: "pending" as const,
    description: "Reparación de frenos",
    estimated_duration: 90,
  },
  {
    id: 3,
    customer_name: "Juan Martínez",
    customer_phone: "+34 634 567 890",
    appointment_date: "2025-10-29T09:00:00",
    status: "confirmed" as const,
    description: "Cambio de neumáticos",
    estimated_duration: 45,
  },
  {
    id: 4,
    customer_name: "Ana Fernández",
    customer_phone: "+34 645 678 901",
    appointment_date: "2025-10-29T11:30:00",
    status: "confirmed" as const,
    description: "Diagnóstico de motor",
    estimated_duration: 120,
  },
]
